// @module O 内容工具箱
//
// PHP 代码生成器（移植自 oblivions/editor/src/lib/php-codegen.js，加 TS 类型）
//
// 将 TS 对象转换为 PHP 数组代码（4 空格缩进、单引号字符串、'key' => value 形式）
// 文件头注入：
//   - <?php if (!defined('IN_GAME')) { exit('Access Denied'); }
//   - @module E 游戏逻辑 标签（对齐 NEW_DESIGN.md §3.2.2）
// 字段过滤：导出 region_*.php 时剥离编辑器专用字段 _breaks（保留 height / destructible / preset_safe）
// pgroup key 类型转换：TS number key 经 Object.keys 转为字符串后，codegen 输出为数字 key（不加引号）
//
// P5-2 新增 generatePhpFile API（执行案 06-P5 §4.2.3）：
//   - 按 schema projectionTargets 派生 PHP 输出（module/sectionTitle/fieldOrder/alignmentStyle）
//   - 文件头注入 `// AUTO-GENERATED FROM oblivions/content/...` 只读保护注释
//   - 字段顺序由 fieldOrder 决定，字段对齐由 alignmentStyle 决定（'space-padded' 用空格补齐）
//   - 字节稳定：相同输入 → 相同输出，不依赖对象 key 插入顺序（fieldOrder 优先）

import type { MapProject, Pgroup, Pls, Tile, Region, Grid } from '../types/map';

/**
 * 序列化目标 TS 值类型
 */
export type CodegenValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | CodegenValue[]
  | { [key: string]: CodegenValue };

/**
 * P5-2 PHP 值类型——generatePhpFile API 使用。
 *
 * 与 CodegenValue 对齐，但不包含 undefined（P5 编译产物不应有 undefined 字段）。
 */
export type PhpValue =
  | string
  | number
  | boolean
  | null
  | PhpValue[]
  | { [key: string]: PhpValue };

/**
 * P5-2 generatePhpFile 选项——按 schema projectionTargets 派生 PHP 输出。
 *
 * 字段说明：
 *   - module：PHP 文件头 `@module` 标签（如 'F 物品系统'）
 *   - sectionTitle：节标题块注释（如 'Oblivions 道具表'）
 *   - autoGeneratedFrom：作者资源 YAML 路径，生成 `// AUTO-GENERATED FROM ...` 只读保护注释
 *   - fieldOrder：字段顺序（entry 级字段输出顺序，未列出的字段按原顺序追加）
 *   - alignmentStyle：'space-padded' 用空格补齐 key（如 `'itm'      =>`），'compact' 紧凑
 *   - groupSeparator：分组注释（保留扩展，暂未使用）
 *   - indent：缩进空格数（默认 4）
 */
export interface PhpCodegenOptions {
  module: string;
  sectionTitle?: string;
  autoGeneratedFrom?: string;
  fieldOrder?: string[];
  alignmentStyle?: 'space-padded' | 'compact';
  groupSeparator?: string;
  indent?: number;
}

/**
 * 标准文件头（含 @module E 游戏逻辑 标签，对齐 NEW_DESIGN.md §3.2.2）
 *
 * 注：@module E 标签用于后端工具识别该文件属于游戏逻辑模块
 */
const PHP_FILE_HEADER = `<?php\nif (!defined('IN_GAME')) { exit('Access Denied'); }\n// @module E 游戏逻辑\n\n`;

/**
 * 生成 map.php 内容
 */
export function generateMapPhp(
  regions: Record<Pgroup, Region>,
  grids: Record<Pgroup, Grid>,
): string {
  const regionsCode = valueToPhp(regions as unknown as CodegenValue, 0);
  const gridsCode = valueToPhp(grids as unknown as CodegenValue, 0);

  return (
    PHP_FILE_HEADER +
    `// ================================================================\n` +
    `// Oblivions 地图数据 — 区域元数据 + 网格布局\n` +
    `// 地图格数据按区域拆分至 tiles/region_{pgroup}.php，按需加载\n` +
    `// 数据结构：regions[pgroup] + grids[pgroup]\n` +
    `// pls 范围 1-254，区域内局部索引，pls=0 保留不使用\n` +
    `// ================================================================\n\n` +
    `return [\n` +
    `    'regions' => ${regionsCode},\n` +
    `    'grids' => ${gridsCode},\n` +
    `];\n`
  );
}

/**
 * 生成 region_*.php 内容
 *
 * 自动剥离编辑器专有字段 _breaks
 */
export function generateRegionPhp(
  pgroup: Pgroup,
  tiles: Record<Pls, Tile>,
): string {
  const regionName = tiles && Object.keys(tiles).length > 0 ? '区域数据' : '空区域';

  // 过滤编辑器专有字段（_breaks）
  const cleanTiles = stripEditorFields(tiles);

  return (
    PHP_FILE_HEADER +
    `// ================================================================\n` +
    `// Oblivions 地图格数据 — 区域 ${pgroup}：${regionName}\n` +
    `// pls 范围 1-254，区域内局部索引\n` +
    `// ================================================================\n\n` +
    `return ${valueToPhp(cleanTiles as unknown as CodegenValue, 0)};\n`
  );
}

/**
 * 生成配置文件 PHP 内容（scatter_pool / poi_table / poi_pool 通用）
 */
export function generateConfigPhp(
  name: string,
  description: string,
  data: CodegenValue,
): string {
  return (
    PHP_FILE_HEADER +
    `// ================================================================\n` +
    `// Oblivions 配置文件 — ${name}\n` +
    `// ${description}\n` +
    `// ================================================================\n\n` +
    `return ${valueToPhp(data, 0)};\n`
  );
}

/**
 * P5-2 按 schema projectionTargets 派生 PHP 文件内容（执行案 06-P5 §4.2.3）。
 *
 * 输出结构：
 *   <?php
 *   // AUTO-GENERATED FROM {autoGeneratedFrom}        ← 只读保护注释（若设置）
 *   // DO NOT EDIT MANUALLY - modify the source YAML and recompile
 *
 *   /**
 *    * @module {module}
 *    *\/
 *   if (!defined('IN_GAME')) { exit('Access Denied'); }
 *
 *   // ================================================================
 *   // {sectionTitle}                                  ← 节标题块注释（若设置）
 *   // ================================================================
 *
 *   return [...];
 *
 * 字段顺序与对齐：
 *   - fieldOrder 仅作用于 entry 级（depth=1）字段，未列出的字段按原顺序追加
 *   - alignmentStyle='space-padded' 时，entry 级字段 key（含引号）补齐到该 entry 内最长 key
 *   - 顶层 entry ID key 不对齐（不同 entry ID 长度差异大，对齐反而破坏可读性）
 *   - 嵌套层级（depth≥2）一律 compact，避免对齐噪声扩散到嵌套结构
 *
 * 字节稳定：相同 data + 相同 options → 相同输出。fieldOrder 决定字段顺序，不依赖
 * 对象 key 插入顺序；alignmentStyle 仅依赖 entry 内字段集合（确定性）。
 *
 * @param data PHP 值（通常是 Record<entryId, entry>）
 * @param options 派生选项（来自 schema.projectionTargets[0]）
 */
export function generatePhpFile(data: PhpValue, options: PhpCodegenOptions): string {
  const indent = options.indent ?? 4;
  const lines: string[] = [];

  // PHP 起始标签
  lines.push('<?php');

  // AUTO-GENERATED 只读保护注释（P5 §4.8.2 编译产物头部标识）
  if (options.autoGeneratedFrom) {
    lines.push(`// AUTO-GENERATED FROM ${options.autoGeneratedFrom}`);
    lines.push('// DO NOT EDIT MANUALLY - modify the source YAML and recompile');
    lines.push('');
  }

  // 模块标签块
  lines.push('/**');
  lines.push(` * @module ${options.module}`);
  lines.push(' */');

  // IN_GAME 守卫
  lines.push("if (!defined('IN_GAME')) { exit('Access Denied'); }");
  lines.push('');

  // 节标题块注释
  if (options.sectionTitle) {
    lines.push('// ================================================================');
    lines.push(`// ${options.sectionTitle}`);
    lines.push('// ================================================================');
    lines.push('');
  }

  // 主体：return [...];
  const body = renderPhpValue(data, 0, {
    fieldOrder: options.fieldOrder,
    alignmentStyle: options.alignmentStyle,
    indent,
    applyAlignment: false, // 顶层 entry ID key 不对齐
  });
  lines.push(`return ${body};`);
  lines.push(''); // 文件末尾换行

  return lines.join('\n');
}

/**
 * 移除编辑器专有字段（_breaks 等）
 *
 * 保留所有后端字段（含 height / destructible / preset_safe / neighbors）
 */
export function stripEditorFields(
  tiles: Record<Pls, Tile>,
): Record<Pls, Omit<Tile, '_breaks'>> {
  const result: Record<Pls, Omit<Tile, '_breaks'>> = {} as Record<
    Pls,
    Omit<Tile, '_breaks'>
  >;
  for (const plsStr of Object.keys(tiles)) {
    const pls = Number(plsStr) as Pls;
    const tile = tiles[pls];
    if (!tile) continue;
    // 解构剥离 _breaks，保留其余字段
    const { _breaks: _breaksIgnored, ...rest } = tile;
    void _breaksIgnored;
    result[pls] = rest as Omit<Tile, '_breaks'>;
  }
  return result;
}

/**
 * 将 TS 值转为 PHP 代码（旧 API，保留向后兼容）
 */
export function valueToPhp(val: CodegenValue, indent: number): string {
  if (val === null || val === undefined) return 'null';
  if (typeof val === 'boolean') return val ? 'true' : 'false';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'string') return stringToPhp(val);

  if (Array.isArray(val)) {
    return arrayToPhp(val, indent);
  }

  if (typeof val === 'object') {
    return objectToPhp(val as { [key: string]: CodegenValue }, indent);
  }

  return 'null';
}

// ─── P5-2 内部渲染类型与函数 ─────────────────────────────────────────

/**
 * 渲染选项——传递给内部 render* 函数。
 *
 * applyAlignment 标记当前层级是否应用 fieldOrder+alignmentStyle：
 *   - 顶层（entry map）：false（entry ID key 不对齐）
 *   - entry 级（depth=1）：由 renderPhpObject 按 depth 判断，true（字段 key 对齐）
 *   - 嵌套级（depth≥2）：false（compact，避免对齐扩散）
 *
 * 注：applyAlignment 字段已废弃，保留仅为向后兼容。实际对齐判断由 depth===1 决定。
 */
interface RenderOptions {
  fieldOrder?: string[];
  alignmentStyle?: 'space-padded' | 'compact';
  indent: number;
  applyAlignment: boolean;
}

/**
 * 渲染 PhpValue 为 PHP 代码字符串（P5-2 内部函数）。
 *
 * 与旧 valueToPhp 行为一致，但支持 fieldOrder + alignmentStyle。
 */
function renderPhpValue(val: PhpValue, depth: number, opts: RenderOptions): string {
  if (val === null) return 'null';
  if (typeof val === 'boolean') return val ? 'true' : 'false';
  if (typeof val === 'number') return String(val);
  if (typeof val === 'string') return stringToPhp(val);

  if (Array.isArray(val)) {
    return renderPhpArray(val, depth, opts);
  }

  if (typeof val === 'object') {
    return renderPhpObject(val as Record<string, PhpValue>, depth, opts);
  }

  return 'null';
}

/**
 * 渲染索引数组（P5-2 内部函数）
 */
function renderPhpArray(arr: PhpValue[], depth: number, opts: RenderOptions): string {
  if (arr.length === 0) return '[]';

  const pad = ' '.repeat((depth + 1) * opts.indent);
  const closePad = ' '.repeat(depth * opts.indent);
  const items = arr.map((item) => `${pad}${renderPhpValue(item, depth + 1, opts)}`);
  return `[\n${items.join(',\n')}\n${closePad}]`;
}

/**
 * 渲染关联数组/对象（P5-2 内部函数）
 *
 * 当 depth===1（entry 级）且有 fieldOrder 时：
 *   - 按 fieldOrder 重排字段（未列出的字段按原顺序追加）
 *   - alignmentStyle='space-padded' 时 key（含引号）补齐到该对象内最长 key 长度，
 *     并使用 `  => ` 分隔符（2 空格，与现有 PHP 文件风格对齐）
 *
 * 当 depth!==1 或无 fieldOrder 时：
 *   - 字段按原顺序输出
 *   - key 不补齐，使用 ` => ` 分隔符（1 空格）
 */
function renderPhpObject(
  obj: Record<string, PhpValue>,
  depth: number,
  opts: RenderOptions,
): string {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '[]';

  // entry 级（depth===1）应用 fieldOrder + alignmentStyle
  const isEntryLevel = depth === 1;
  const hasFieldOrder = opts.fieldOrder !== undefined && opts.fieldOrder.length > 0;
  const shouldAlign = isEntryLevel && hasFieldOrder;

  // 字段顺序：entry 级且有 fieldOrder 时按 fieldOrder 重排
  let orderedKeys: string[];
  if (shouldAlign) {
    const present = new Set(keys);
    const ordered = opts.fieldOrder!.filter((k) => present.has(k));
    const fieldOrderSet = new Set(opts.fieldOrder!);
    const extra = keys.filter((k) => !fieldOrderSet.has(k));
    orderedKeys = [...ordered, ...extra];
  } else {
    orderedKeys = keys;
  }

  // 计算 max key 长度（含引号）用于 space-padded 对齐
  let maxKeyLen = 0;
  const isSpacePadded = shouldAlign && opts.alignmentStyle === 'space-padded';
  if (isSpacePadded) {
    for (const k of orderedKeys) {
      const keyStr = renderPhpKey(k);
      if (keyStr.length > maxKeyLen) maxKeyLen = keyStr.length;
    }
  }

  const pad = ' '.repeat((depth + 1) * opts.indent);
  const closePad = ' '.repeat(depth * opts.indent);
  // 分隔符：space-padded 时用 `  => `（2 空格），与现有 PHP 文件风格对齐；
  // compact 时用 ` => `（1 空格）
  const separator = isSpacePadded ? '  => ' : ' => ';

  const items = orderedKeys.map((k) => {
    const keyStr = renderPhpKey(k);
    const paddedKey = isSpacePadded ? keyStr.padEnd(maxKeyLen) : keyStr;
    const valStr = renderPhpValue(obj[k]!, depth + 1, opts);
    return `${pad}${paddedKey}${separator}${valStr}`;
  });

  return `[\n${items.join(',\n')}\n${closePad}]`;
}

/**
 * 渲染 PHP key——数字字符串 key 直接用数字（不加引号），否则用单引号字符串。
 *
 * 与旧 objectToPhp 行为一致（pgroup/pls 类型转换）。
 */
function renderPhpKey(key: string): string {
  return /^\d+$/.test(key) ? key : stringToPhp(key);
}

/**
 * 字符串转 PHP 单引号字符串
 */
function stringToPhp(str: string): string {
  const escaped = str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `'${escaped}'`;
}

/**
 * 索引数组转 PHP（旧 API）
 */
function arrayToPhp(arr: CodegenValue[], indent: number): string {
  if (arr.length === 0) return '[]';

  const pad = '    '.repeat(indent + 1);
  const closePad = '    '.repeat(indent);
  const items = arr.map((item) => `${pad}${valueToPhp(item, indent + 1)}`);
  return `[\n${items.join(',\n')}\n${closePad}]`;
}

/**
 * 关联数组（对象）转 PHP
 *
 * pgroup / pls 在 TS 中是 number key，Object.keys 返回字符串后，
 * 数字字符串 key 直接输出为数字（不加引号），其他字符串 key 输出为单引号字符串
 */
function objectToPhp(obj: { [key: string]: CodegenValue }, indent: number): string {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '[]';

  const pad = '    '.repeat(indent + 1);
  const closePad = '    '.repeat(indent);

  const items = keys.map((key) => {
    // 数字字符串 key 直接用数字（不加引号），否则用单引号字符串
    const phpKey = /^\d+$/.test(key) ? key : stringToPhp(key);
    const phpVal = valueToPhp(obj[key]!, indent + 1);
    return `${pad}${phpKey} => ${phpVal}`;
  });

  return `[\n${items.join(',\n')}\n${closePad}]`;
}

/**
 * 将整个 MapProject 序列化为 map.php + 所有 region_*.php 文件映射
 *
 * @param project 地图项目
 * @returns 文件名 → 内容 的映射（key=map.php 或 tiles/region_{pgroup}.php）
 */
export function generateProjectFiles(project: MapProject): Record<string, string> {
  const files: Record<string, string> = {};
  files['map.php'] = generateMapPhp(project.regions, project.grids);
  for (const pgroupStr of Object.keys(project.tiles)) {
    const pgroup = Number(pgroupStr) as Pgroup;
    const tiles = project.tiles[pgroup];
    if (tiles === undefined) continue;
    files[`tiles/region_${pgroup}.php`] = generateRegionPhp(pgroup, tiles);
  }
  return files;
}
