<?php
if (!defined('IN_GAME')) { exit('Access Denied'); }

// ================================================================
// Oblivions 道具模板表
// 唯一 ID 索引 → 道具模板属性
// 其他文件引用道具时只需引用 ID，运行时从此表读取模板实例化
// 字段与现有物品系统对齐：itm/itmk/itme/itms/itmsk/itmpara
// ================================================================

return [
    // ─── 武器 ───────────────────────────────────────────

    'rusty_pipe' => [
        'itm'      => '生锈的水管',
        'itmk'     => 'WP',
        'itme'     => 8,
        'itms'     => 20,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '一根锈迹斑斑的铁管，握在手里沉甸甸的。',
        'tier'     => 'common',
        'stack'    => false,
    ],
    'scrap_blade' => [
        'itm'      => '废铁刀',
        'itmk'     => 'WK',
        'itme'     => 12,
        'itms'     => 15,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '用废铁片磨出的粗糙刀刃，勉强能割开东西。',
        'tier'     => 'common',
        'stack'    => false,
    ],
    'nail_gun' => [
        'itm'      => '钉枪',
        'itmk'     => 'WG',
        'itme'     => 10,
        'itms'     => 8,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '工地上常见的气动钉枪，近距离威力不小。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],
    'pipe_bomb' => [
        'itm'      => '管状炸弹',
        'itmk'     => 'WD',
        'itme'     => 25,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '用铁管和火药自制的简易爆炸物，小心别炸到自己。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],
    'swamp_spear' => [
        'itm'      => '沼泽长矛',
        'itmk'     => 'WK',
        'itme'     => 18,
        'itms'     => 25,
        'itmsk'    => 'p',
        'itmpara'  => '',
        'desc'     => '用沼泽硬木和骨片制成的长矛，尖端涂有毒素。',
        'tier'     => 'rare',
        'stack'    => false,
    ],
    'ancient_core_blade' => [
        'itm'      => '核心刃',
        'itmk'     => 'WF',
        'itme'     => 30,
        'itms'     => 15,
        'itmsk'    => 'f',
        'itmpara'  => '',
        'desc'     => '嵌入古代核心的武器，刃身散发微弱的光辉。',
        'tier'     => 'epic',
        'stack'    => false,
    ],

    // ─── 防具 ───────────────────────────────────────────

    'scrap_vest' => [
        'itm'      => '废铁背心',
        'itmk'     => 'AR',
        'itme'     => 6,
        'itms'     => 30,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '用铁皮和铁丝拼凑的简易护甲，聊胜于无。',
        'tier'     => 'common',
        'stack'    => false,
    ],
    'swamp_cloak' => [
        'itm'      => '沼泽斗篷',
        'itmk'     => 'AR',
        'itme'     => 10,
        'itms'     => 25,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '用沼泽藤蔓编织的斗篷，能抵御部分攻击。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],
    'rust_circlet' => [
        'itm'      => '锈蚀头环',
        'itmk'     => 'AH',
        'itme'     => 4,
        'itms'     => 20,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '锈蚀的金属头环，提供基本的头部防护。',
        'tier'     => 'common',
        'stack'    => false,
    ],
    'bone_amulet' => [
        'itm'      => '骨制护符',
        'itmk'     => 'AA',
        'itme'     => 5,
        'itms'     => 15,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '用不明骨骼雕刻的护符，散发着诡异的气息。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],

    // ─── 消耗品 ─────────────────────────────────────────

    'bread' => [
        'itm'      => '面包',
        'itmk'     => 'HH',
        'itme'     => 120,
        'itms'     => 15,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '朴素的干面包，能快速补充生命。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 5,
    ],
    'mineral_water' => [
        'itm'      => '矿泉水',
        'itmk'     => 'HS',
        'itme'     => 140,
        'itms'     => 15,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '未开封的瓶装水，能恢复体力。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 5,
    ],

    'scrap_metal' => [
        'itm'      => '废铁片',
        'itmk'     => 'MT',
        'itme'     => 5,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '锈迹斑斑的金属碎片，也许能派上用场。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 10,
    ],
    'rusty_gear' => [
        'itm'      => '生锈齿轮',
        'itmk'     => 'MT',
        'itme'     => 3,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '废弃机械中拆下的齿轮，也许能合成什么。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 10,
    ],
    'health_potion' => [
        'itm'      => '生命药剂',
        'itmk'     => 'HH',
        'itme'     => 80,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '注入了回复魔力的红色液体，饮用后恢复生命。',
        'tier'     => 'uncommon',
        'stack'    => true,
        'stack_limit' => 5,
    ],
    'stamina_potion' => [
        'itm'      => '体力药剂',
        'itmk'     => 'HS',
        'itme'     => 50,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '淡绿色的液体，饮用后恢复体力。',
        'tier'     => 'uncommon',
        'stack'    => true,
        'stack_limit' => 5,
    ],
    'supply_pack' => [
        'itm'      => '补给包',
        'itmk'     => 'HH',
        'itme'     => 30,
        'itms'     => 3,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '简易的急救补给，可多次使用。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 3,
    ],
    'antidote' => [
        'itm'      => '解毒剂',
        'itmk'     => 'DX',
        'itme'     => 1,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '能中和常见毒素的药剂，沼泽中不可或缺。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 5,
    ],
    'swamp_herb' => [
        'itm'      => '沼泽草药',
        'itmk'     => 'HH',
        'itme'     => 20,
        'itms'     => 1,
        'itmsk'    => 'p',
        'itmpara'  => '',
        'desc'     => '沼泽中生长的草药，能恢复少量生命但有轻微毒性。',
        'tier'     => 'common',
        'stack'    => true,
        'stack_limit' => 8,
    ],
    'ancient_core' => [
        'itm'      => '古代核心',
        'itmk'     => 'MT',
        'itme'     => 50,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '散发微光的神秘核心，蕴含未知的能量。',
        'tier'     => 'rare',
        'stack'    => false,
    ],

    // ─── 工具 ───────────────────────────────────────────

    'rope_coil' => [
        'itm'      => '绳索',
        'itmk'     => 'TK',
        'itme'     => 1,
        'itms'     => 3,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '一卷结实的绳索，在沼泽地带可能派上用场。',
        'tier'     => 'common',
        'stack'    => false,
    ],
    'compass' => [
        'itm'      => '指南针',
        'itmk'     => 'TK',
        'itme'     => 1,
        'itms'     => 999,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '老旧但还能用的指南针，在迷雾中辨别方向。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],
    'lockpick' => [
        'itm'      => '开锁器',
        'itmk'     => 'TK',
        'itme'     => 1,
        'itms'     => 5,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '简易的开锁工具，也许能打开某些宝箱。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],

    // ─── 特殊 ───────────────────────────────────────────

    'element_pocket' => [
        'itm'      => '元素口袋',
        'itmk'     => 'SP',
        'itme'     => 1,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '能收纳元素之力的神秘口袋，元素大师专属道具。',
        'tier'     => 'rare',
        'stack'    => false,
    ],
    'mystery_box' => [
        'itm'      => '神秘礼盒',
        'itmk'     => 'SP',
        'itme'     => 1,
        'itms'     => 1,
        'itmsk'    => '',
        'itmpara'  => '',
        'desc'     => '包装精美的礼盒，打开后才知道里面是什么。',
        'tier'     => 'uncommon',
        'stack'    => false,
    ],
];
